version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "dbFinBank"
      MYSQL_USER: "finbankJavaApp"
      MYSQL_PASSWORD: "app123654678"
    ports:
      - "3306:3306"